"""
Django settings for test_app project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from params import DROPBOX_ACCESS_TOKEN_VALUE, DATABASES_SETTING

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'akoikelov.djazz',
    'test_app'
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    },
]

DATABASES = DATABASES_SETTING

SECRET_KEY = "secret_key_for_testing"
DROPBOX_ACCESS_TOKEN = DROPBOX_ACCESS_TOKEN_VALUE
MEDIA_ROOT = 'media'
TIME_ZONE = 'Asia/Bishkek'
